import "%modules%/footer/footer"
import "%modules%/sections/s-persons/s-persons";
import "%modules%/sections/s-gratitude/s-gratitude";
import "%modules%/quiz/block-final";
import "%modules%/quiz/popup-quiz";
import "%modules%/sections/s-what-get-bottom/adv-card/adv-card";
import "%modules%/modals/left-phone/left-phone";
import "%modules%/modals/new-exit-popup/new-exit-popup";
import "%modules%/fake-video/fake-video";
